<?xml version="1.0" encoding="windows-1251"?>
<style>
.app-bar {
	background-color: #1787c6;
}
</style>
<div class="app-bar block-shadow">
    <ul class="app-bar-menu small-dropdown">
        <li>
            <a href="plan.asp?sem=0" class="dropdown-toggle">Учебный план</a>
            <ul class="d-menu" data-role="dropdown">
				<li><a href="plan.asp?sem=1">I семестр</a></li>
                <li><a href="plan.asp?sem=2">II семестр</a></li>
                <li><a href="#" class="dropdown-toggle bg-green fg-white bg-hover-darkGreen">Редактировать</a>
                    <ul class="d-menu" data-role="dropdown">
                        <li><a href="#">Группы</a></li>
                        <li><a href="#">Специальности</a></li>
                        <li><a href="#">Пользователи</a></li>
                    </ul>
                </li>
				<li><a href="nakopl.asp">Накопляемость</a></li>
				<li><a href="#">Страница 1.6</a></li>
				<li><a href="#">Страница 1.7</a></li>
            </ul>
        </li>
        <li>
            <a class="dropdown-toggle">Раздел 2</a>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">Страница 2</a></li>
				<li><a href="#">Страница 2.1</a></li>
                <li><a href="#">Страница 2.2</a></li>
				<li><a href="#">Страница 2.3</a></li>
				<li><a href="#">Страница 2.4</a></li>
				<li><a href="#">Страница 2.5</a></li>
            </ul>
        </li>
		<li>
            <a class="dropdown-toggle">Раздел 3</a>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">Страница 3</a></li>
				<li><a href="#">Страница 3.1</a></li>
                <li><a href="#">Страница 3.2</a></li>
				<li><a href="#">Страница 3.3</a></li>
				<li><a href="#">Страница 3.4</a></li>
				<li><a href="#">Страница 3.5</a></li>
            </ul>
        </li>
		<li>
            <a class="dropdown-toggle">Статистика</a>
            <ul class="d-menu" data-role="dropdown">
                <li><a href="#">Ошибки</a></li>
				<li><a href="#">Занятия</a></li>
                <li><a href="#">Оценки</a></li>
				<li><a href="#" class="dropdown-toggle bg-green fg-white bg-hover-darkGreen">Ввод данных</a>
                    <ul class="d-menu" data-role="dropdown">
                        <li><a href="#">Занятия</a></li>
                        <li><a href="#">Оценки</a></li>
                    </ul>
                </li>
				<li><a href="rate_update.asp?confirm=1">Обновление рейтинга</a></li>
				<li><a href="stud_update.asp?confirm=1">Перевод курсов</a></li>
            </ul>
        </li>
    </ul>
</div>